version: '3'
services:
  backend:
    build:
      context: ./backend
    image: "fastapi"
    volumes:
      - ./backend:/src
    ports:
      - "9004:9004"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 9004

  frontend:
    build:
      context: ./frontend
    image: "vuev2"
    volumes:
      - ./frontend:/src
    ports:
      - 8080:8080
    tty: true