version: '3'
services:
  backend:
    build:
      context: ./backend
    image: "fastapi"
    ports: 
      - 8000:8000
    volumes:
      - ./backend:/src
    tty: true

  frontend:
    build:
      context: ./frontend
    image: "vuev2"
    volumes:
      - ./frontend:/src
    tty: true